# Generated by Django 5.1.7 on 2025-03-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_cpf', models.CharField(default='', max_length=11, primary_key=True, serialize=False)),
                ('user_name', models.CharField(default='', max_length=150)),
                ('user_age', models.IntegerField(default=0)),
                ('user_telephone', models.IntegerField(default=0)),
                ('user_email', models.EmailField(default='', max_length=254)),
            ],
        ),
    ]
