# Generated by Django 5.1.7 on 2025-03-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_cpf',
            field=models.CharField(default='', max_length=11),
        ),
    ]
