# Generated by Django 5.1.7 on 2025-03-29 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_manager_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='users',
        ),
    ]
