# Generated by Django 5.1.7 on 2025-03-29 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_manager_api', '0002_alter_customuser_options_alter_customuser_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orgaos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sigla', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'orgaos',
            },
        ),
        migrations.RemoveField(
            model_name='atores',
            name='email',
        ),
        migrations.RemoveField(
            model_name='atores',
            name='nome',
        ),
        migrations.AddField(
            model_name='customuser',
            name='atores_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='auth_manager_api.atores'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='orgao_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth_manager_api.orgaos'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=255)),
                ('data_inicio', models.DateField()),
                ('data_final', models.DateField()),
                ('atores_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_manager_api.atores')),
                ('projeto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'projetos',
            },
        ),
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=255)),
                ('data_inicio', models.DateField()),
                ('data_final', models.DateField()),
                ('orgao_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_manager_api.orgaos')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tarefas',
            },
        ),
    ]
