# Generated by Django 5.1.7 on 2025-03-29 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_manager_api', '0003_orgaos_remove_atores_email_remove_atores_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='orgao_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_manager_api.orgaos'),
        ),
    ]
