# Generated by Django 5.1.7 on 2025-03-29 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_manager_api', '0005_alter_customuser_atores_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetos',
            name='atores_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_manager_api.atores'),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='projeto_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='orgao_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_manager_api.orgaos'),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='usuario_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
