# Generated by Django 5.1.7 on 2025-03-30 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_manager_api', '0006_alter_projetos_atores_id_alter_projetos_projeto_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefas',
            old_name='usuario_id',
            new_name='responsavel_id',
        ),
        migrations.RemoveField(
            model_name='projetos',
            name='atores_id',
        ),
        migrations.RemoveField(
            model_name='projetos',
            name='projeto_id',
        ),
        migrations.AddField(
            model_name='projetos',
            name='analista_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proj_analista', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projetos',
            name='desenvolvedor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proj_desenvolvedor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projetos',
            name='orgao_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_manager_api.orgaos'),
        ),
        migrations.AddField(
            model_name='tarefas',
            name='projeto_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_manager_api.projetos'),
        ),
    ]
