# Generated by Django 5.1.7 on 2025-05-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_manager_api', '0009_alter_customuser_atores_id_alter_customuser_orgao_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefas',
            name='status',
            field=models.CharField(default='Em andamento', max_length=50),
        ),
    ]
