# Generated by Django 5.1.7 on 2025-05-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_manager_api', '0010_tarefas_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetos',
            name='status',
            field=models.CharField(default='Em andamento', max_length=50),
        ),
    ]
