# Generated by Django 5.1.7 on 2025-05-09 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_manager_api', '0010_mensagens'),
        ('auth_manager_api', '0011_projetos_status'),
    ]

    operations = [
    ]
