# Generated by Django 5.1.7 on 2025-05-16 10:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_manager_api', '0012_merge_0010_mensagens_0011_projetos_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetos',
            name='membros',
            field=models.ManyToManyField(blank=True, related_name='projetos_participando', to=settings.AUTH_USER_MODEL),
        ),
    ]
